name: Generate Snake Game

on:
  schedule:       # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Manual trigger

permissions:
  contents: write   # Needed to push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3
        with:
          persist-credentials: true   # Allows using GITHUB_TOKEN for pushes

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install the snake animation tool globally
      - name: Install snk
        run: npm install -g @sutil/snk

      # Generate snake animation SVG
      - name: Generate Snake SVG
        run: |
          mkdir -p dist
          snk -u ${{ github.repository_owner }} -o dist/github-contribution-grid-snake2.svg -c blue

      # Commit and push the updated SVG to main
      - name: Commit and Push
        run: |
          git config --global user.name "${{ github.repository_owner }}"
          git config --global user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git add dist/github-contribution-grid-snake2.svg
          git commit -m "Update snake animation"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.first_token }}
